services:
  flask:
    build:
      context: .
    container_name: flask_app
    expose:
      - "8000"  # Flask internal portu no need for port mapping
    environment:
      - FLASK_ENV=development
    restart: unless-stopped

    networks:
      - backend 
   
   

  nginx:
    image: nginx:alpine
    container_name: nginx_server
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Nginx configuration file
    ports:
      - "80:80"
    depends_on:
      - flask
    restart: unless-stopped

    networks:
      - backend 
       # Nginx also connects to the same 'backend' network

 
networks:
  backend:
    driver: bridge
