FROM python:3.10  # Python tabanlı bir imaj kullan
WORKDIR /app       # Çalışma dizinini belirle
COPY . /app        # Dosyaları konteynıra kopyala

CMD ["python", "app.py"]  # Konteyner başladığında Flask uygulamasını çalıştır
